#------------------
#   SPACESHIP
#------------------

SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_CHAR_SYMBOL='|> '
SPACESHIP_CHAR_COLOR_SUCCESS=white
SPACESHIP_CHAR_COLOR_FAILURE=red
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR=white
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_USER_SHOW=true
SPACESHIP_HOST_SHOW=true
SPACESHIP_HOST_SHOW_FULL=false
SPACESHIP_USER_PREFIX='as '
SPACESHIP_HOST_PREFIX=' at '
SPACESHIP_DIR_COLOR=yellow
SPACESHIP_DIR_PREFIX='[ '
SPACESHIP_DIR_SUFFIX=' ] '
SPACESHIP_DIR_TRUNC_PREFIX='.../'
SPACESHIP_DIR_LOCK_SYMBOL=' '
SPACESHIP_GIT_BRANCH_COLOR=cyan
